# Generated by Django 6.0.5 on 2026-05-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('waste_collection', 'Waste Collection'), ('tree_planting', 'Tree Planting'), ('urban_farming', 'Urban Farming'), ('climate_data', 'Climate Data Collection'), ('recycling', 'Recycling & Sorting'), ('community_education', 'Community Education')], max_length=50)),
                ('description', models.TextField()),
                ('location_lga', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('workers_needed', models.PositiveIntegerField(default=1)),
                ('workers_accepted', models.PositiveIntegerField(default=0)),
                ('pay_per_worker', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_volunteer_only', models.BooleanField(default=False)),
                ('proof_requirements', models.TextField(blank=True)),
                ('day_of_contact_name', models.CharField(blank=True, max_length=150)),
                ('day_of_contact_phone', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('submitted', 'Proof Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='accepted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payout_notified', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('task', 'worker')},
            },
        ),
    ]
