# Generated by Django 5.0.4 on 2026-05-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_validation_passed', models.BooleanField(blank=True, null=True)),
                ('ai_validation_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_submission', to='tasks.taskassignment')),
            ],
            options={
                'verbose_name': 'Proof Submission',
            },
        ),
        migrations.CreateModel(
            name='ProofPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', 'Task Start'), ('during', 'During Task'), ('completion', 'Task Completion')], max_length=20)),
                ('image', models.ImageField(upload_to='proof_photos/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ai_flag', models.BooleanField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_label', models.CharField(blank=True, max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proof.proofsubmission')),
            ],
            options={
                'verbose_name': 'Proof Photo',
                'ordering': ['captured_at'],
            },
        ),
    ]
